Repository MediBird/caring-note-web, pull requests merged in 2025-04, with the labels that each got.

#222 fix: :arrow_up: update vite version due to vulnerability
  package.json
  pnpm-lock.yaml
Labels: D-1

#223 feat: :fire: 녹음 프로세스 중 STT 발화자 선택 stage 제거
  src/components/common/NavigationLeft.tsx
  src/components/common/NavigationRight.tsx
  src/components/consult/PencilIcon.tsx
  src/components/consult/Recording.tsx
  src/pages/Consult/components/CheckLeaveOutDialog.tsx
  src/pages/Consult/components/FinishConsultDialog.tsx
  src/pages/Consult/components/TemporarySaveDialog.tsx
  src/pages/Consult/components/recording/SelectSpeakerDialog.tsx
  src/pages/Consult/hooks/query/counselRecording/useGetRecordingSpeakersQuery.ts
  src/pages/Consult/index.tsx
Labels: D-3

#224 fix: :recycle: enable boolean button to be null
  src/api/models/allergy-dto.ts
  src/api/models/medication-side-effect-dto.ts
  src/pages/Survey/components/tabs/HealthInfo.tsx
  src/pages/Survey/components/tabs/LivingInfo.tsx
Labels: D-3

#226 hotfix: :bug 상담기록 하이라이트 파싱 수정
  src/pages/Consult/components/tabs/PastConsult.tsx
Labels: D-3

#227 fix: :boom: resolve qa problems
  pnpm-lock.yaml
  src/api/api/aiapi.ts
  src/api/api/aicounsel-summary-controller-api.ts
  src/api/models/add-medication-counsel-req.ts
  src/api/models/analyse-text-req.ts
  src/api/models/select-medication-counsel-res.ts
  src/api/models/select-previous-medication-counsel-res.ts
  src/api/models/update-counselee-req.ts
  src/components/common/DataTable/medicine-search-cell.tsx
  src/components/ui/datepicker.tsx
  src/hooks/useRecording.ts
  src/pages/Consult/components/table/MedicineRecordTable/medicineRecordTableColumns.tsx
  src/pages/Consult/hooks/query/counselRecording/useSendSpeakersQuery.tsx
  src/pages/Consult/hooks/query/useMedicineConsultQuery.ts
  src/pages/Consult/hooks/store/useMedicationConsultStore.ts
  src/pages/Consult/hooks/useInitializeAllTabsData.ts
  src/pages/Consult/types/MedicineConsultDTO.ts
  src/pages/Survey/components/tabs/BasicInfo.tsx
  src/pages/Survey/components/tabs/HealthInfo.tsx
  src/pages/Survey/hooks/useCounselCardQuery.ts
  src/pages/Survey/index.tsx
  src/utils/constants.ts
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: D-3

#228 feat: :sparkles: add toast for counselee queries
  src/pages/Counselee/components/dialog/CounseleeDialog.tsx
  src/pages/Counselee/hooks/query/useCounseleeQuery.ts
  src/pages/Counselee/hooks/query/useFilterOptionsQuery.ts
  src/pages/Counselee/hooks/store/useCounseleeInfoStore.ts
  src/pages/Counselee/hooks/store/useFilterStore.ts
  src/pages/Counselee/hooks/useCounseleeManagement.ts
  src/utils/inputValidations.ts
Labels: D-3

#230 fix: :pencil2: fix toast typos
  src/pages/Counselee/hooks/query/useCounseleeQuery.ts
Labels: bug, D-0

#231 fix: 🐛 중재기록 상태 업데이트 버그 수정
  src/components/consult/HighlightInput.tsx
  src/pages/Consult/hooks/useInitializeAllTabsData.ts
  src/utils/parseEditorContent.ts
Labels: bug, D-1

#232 fix: modify hint text of district placeholder in counselee dialog
  src/pages/Counselee/components/dialog/CounseleeDialog.tsx
Labels: bug, D-3

#233 refactor: :lipstick: update font to dynamic subset
  src/components/common/NavigationLeft.tsx
  src/fonts/Pretendard-Black.woff
  src/fonts/Pretendard-Black.woff2
  src/fonts/Pretendard-Bold.woff
  src/fonts/Pretendard-Bold.woff2
  src/fonts/Pretendard-ExtraBold.woff
  src/fonts/Pretendard-ExtraBold.woff2
  src/fonts/Pretendard-ExtraLight.woff
  src/fonts/Pretendard-ExtraLight.woff2
  src/fonts/Pretendard-Light.woff
  src/fonts/Pretendard-Light.woff2
  src/fonts/Pretendard-Medium.woff
  src/fonts/Pretendard-Medium.woff2
  src/fonts/Pretendard-Regular.woff
  src/fonts/Pretendard-Regular.woff2
  src/fonts/Pretendard-SemiBold.woff
  src/fonts/Pretendard-SemiBold.woff2
  src/fonts/Pretendard-Thin.woff
  src/fonts/Pretendard-Thin.woff2
  src/fonts/PretendardVariable.woff2
  src/index.css
  src/pages/Consult/hooks/useInitializeAllTabsData.ts
  src/pages/Consult/index.tsx
  src/pages/Home/index.tsx
  src/pages/Survey/components/tabs/BasicInfo.tsx
Labels: D-2

#235 docs: :memo: 프로젝트 readme lefthook 내용 추가
  README.md
Labels: D-3

#237 fix: :green_heart: fix ci build
  .github/workflows/deployment-main.yml
  .github/workflows/deployment-staging.yml
  Dockerfile
Labels: D-3

#238 fix: :green_heart: modify deployment action files (check out misssing)
  .github/workflows/auto-pr-from-staging.yml
  .github/workflows/deployment-staging.yml
  package.json
Labels: D-3

#240 feature:add api apth env
  .env
  .github/workflows/auto-pr-from-staging.yml
  .github/workflows/deployment-main.yml
  .github/workflows/deployment-staging.yml
  Dockerfile
  src/api/base.ts
Labels: D-3

#243 chore: .env 파일 삭제 및 .gitignore에 .env 관련 항목 추가
  .env
  .gitignore
Labels: D-3

#249 feat: 💄 add more information on survey
  package.json
  pnpm-lock.yaml
  src/api/.openapi-generator/FILES
  src/api/api/aiapi.ts
  src/api/api/aicounsel-summary-controller-api.ts
  src/api/api/counsel-card-controller-api.ts
  src/api/api/counsel-session-controller-api.ts
  src/api/api/counselee-consent-controller-api.ts
  src/api/api/counselee-controller-api.ts
  src/api/api/counselor-controller-api.ts
  src/api/api/default-api.ts
  src/api/api/medication-controller-api.ts
  src/api/api/medication-counsel-controller-api.ts
  src/api/api/medication-record-hist-controller-api.ts
  src/api/api/waste-medication-controller-api.ts
  src/api/models/add-and-update-medication-record-hist-req.ts
  src/api/models/add-and-update-waste-medication-record-req.ts
  src/api/models/add-counselee-consent-req.ts
  src/api/models/add-medication-counsel-req.ts
  src/api/models/convert-speech-to-text-req.ts
  src/api/models/create-counsel-reservation-req.ts
  src/api/models/delete-aicounsel-summary-req.ts
  src/api/models/delete-counsel-session-req.ts
  src/api/models/delete-counselee-batch-req.ts
  src/api/models/delete-counselee-batch-res.ts
  src/api/models/delete-medication-counsel-req.ts
  src/api/models/index.ts
  src/api/models/medication-management-dto.ts
  src/api/models/modify-counsel-reservation-req.ts
  src/api/models/nutrition-dto.ts
  src/api/models/reset-password-req.ts
  src/api/models/update-counselee-consent-req.ts
  src/api/models/update-counselee-req.ts
  src/api/models/update-counselor-in-counsel-session-req.ts
  src/api/models/update-medication-counsel-req.ts
  src/api/models/update-status-in-counsel-session-req.ts
  src/hooks/useRecording.ts
  src/pages/Account/components/dialog/AccountDetailDialog.tsx
  src/pages/Account/components/dialog/BasicInfoTab.tsx
  src/pages/Account/components/table/AccountTable.tsx
  src/pages/Account/components/table/CounselorColumns.tsx
  src/pages/Account/hooks/store/useCounselorStore.ts
  src/pages/Consult/components/tabs/ConsultCard.tsx
  src/pages/Consult/hooks/query/counselRecording/useSendSpeakersQuery.tsx
  src/pages/Home/hooks/query/useCounselAssign.ts
  src/pages/Survey/components/tabs/LivingInfo.tsx
  src/pages/Survey/consent.tsx
  src/utils/constants.ts
Labels: D-3
