Repository MediBird/caring-note-web, pull requests merged in 2025-03, with the labels that each got.

#154 feat: :sparkles: add pr template and rules
  .github/pull_request_template.md
  .github/workflows/d-day-auto-labeler.yml
  .github/workflows/d-day-labeler.yml
Labels: D-3

#157 refactor: :lipstick: refactor table-filter
  .github/workflows/d-day-auto-labeler.yml
  src/components/common/DataTable/table-filter.tsx
Labels: D-3

#158 feat: 🎨 메인페이지 브랜딩 디자인 적용
  src/assets/home/counselee-stats.webp
  src/assets/home/done-stats.webp
  src/assets/home/home-bg.webp
  src/assets/home/logo-wide.webp
  src/assets/home/message-stats.webp
  src/assets/home/table-empty.webp
  src/assets/home/times-stats.webp
  src/assets/text-logo.webp
  src/components/CollegeMessage.tsx
  src/components/ConsultCount.tsx
  src/components/common/DataTable/data-table.tsx
  src/components/ui/datepicker.tsx
  src/lib/getTableCellPinningStyle.ts
  src/pages/Consult/index.tsx
  src/pages/Home/components/CollegeMessages.tsx
  src/pages/Home/components/ConsultCount.tsx
  src/pages/Home/components/ConsultCountContainer.tsx
  src/pages/Home/components/TodayScheduleTable/index.tsx
  src/pages/Home/index.tsx
  tailwind.config.js
Labels: D-3

#159 feat(STT): ✨ add recording image by case
  src/assets/recording/recording.webp
  src/assets/recording/recordingComplete.webp
  src/assets/recording/recordingDialog.webp
  src/assets/recording/recordingWaiting.webp
  src/assets/recordingDialog.png
  src/assets/recordingDialog_old.png
  src/components/consult/Recording.tsx
  src/pages/Consult/components/recording/RecordingDialog.tsx
  src/pages/Consult/components/recording/RecordingResult.tsx
  src/pages/Consult/components/tabs/MedicineConsult.tsx
Labels: D-3

#163 refactor: :recycle: refactor UX of search or filter mechanism
  src/components/common/search-input.tsx
  src/pages/Counselee/hooks/useCounseleeManagement.ts
  src/pages/Counselee/index.tsx
  src/pages/Layout.tsx
  src/pages/Session/components/CounselSessionTableSection.tsx
  src/pages/Session/components/FilterSection.tsx
  src/pages/Session/components/table/CounselSessionColumns.tsx
  src/pages/Session/components/table/CounselSessionTable.tsx
  src/pages/Session/components/table/ScheduleTable.tsx
  src/pages/Session/hooks/store/useCounselSessionStore.tsx
  src/pages/Session/index.tsx
Labels: bug, D-0

#164 fix: 💄 중재기록작성 UI 수정 및 SNB 변경사항 반영
  src/assets/warning.webp
  src/components/NavigationRight.tsx
  src/components/consult/HighlightInput.tsx
  src/components/consult/Recording.tsx
  src/pages/Consult/components/recording/AiSummary.tsx
  src/pages/Consult/components/recording/RecordingResult.tsx
  src/pages/Consult/components/recording/TotalRecordings.tsx
  src/pages/Consult/components/tabs/MedicineConsult.tsx
Labels: D-4

#165 refactor: 캘린더, 테이블 텍스트 레이아웃, 스크롤관련 스타일 수정
  src/assets/icon/24/arrowleft.outlined.svg
  src/assets/icon/24/arrowright.outlined.svg
  src/components/common/DataTable/data-table.tsx
  src/components/common/DataTable/text-input-cell.tsx
  src/components/ui/buttonVariants.ts
  src/components/ui/calendar.tsx
  src/components/ui/datepicker.tsx
  src/components/ui/table.tsx
  src/pages/Consult/components/table/WasteMedicationTable/wasteMedicationColumns.tsx
  src/pages/Consult/index.tsx
  src/pages/Home/components/TodayScheduleTable/todayScheduleTableColumn.tsx
  src/pages/Home/index.tsx
  src/pages/Layout.tsx
Labels: D-3

#166 feat: ✨ add error pages
  src/app/Routes.tsx
  src/assets/illusts/404.webp
  src/assets/illusts/check.webp
  src/assets/illusts/empty.webp
  src/assets/illusts/general-error.webp
  src/assets/illusts/maintenance.webp
  src/assets/illusts/network-error.webp
  src/assets/illusts/nope.webp
  src/assets/illusts/onlypc.webp
  src/assets/illusts/sleep.webp
  src/components/common/NavigationLeft.tsx
  src/pages/Counselee/components/dialog/CounseleeDialog.tsx
  src/pages/Counselee/hooks/useCounseleeManagement.ts
  src/pages/ErrorPage.tsx
  src/pages/Errors/ErrorCommon.tsx
  src/pages/Errors/Forbidden.tsx
  src/pages/Errors/NotFound.tsx
Labels: D-3

#167 refactor: :art: LNB UI 다자인 필터링 QA 반영
  src/assets/home/counselee-stats.webp
  src/assets/home/done-stats.webp
  src/assets/home/home-bg.webp
  src/assets/home/logo-wide.webp
  src/assets/home/message-stats.webp
  src/assets/home/times-stats.webp
  src/assets/icon/24/accountcircle.fiiled.svg
  src/assets/icon/24/logout.outline.svg
  src/assets/text-logo.webp
  src/components/common/NavigationLeft.tsx
  src/components/ui/button.tsx
  src/components/ui/buttonVariants.ts
  src/components/ui/sidebar.tsx
  src/components/ui/table.tsx
  src/index.css
  src/pages/Home/components/AssignDialog.tsx
  src/pages/Home/components/ConsultCountContainer.tsx
  src/pages/Home/components/TodayScheduleTable/todayScheduleTableColumn.tsx
  src/pages/Home/index.tsx
  src/store/navigationStore.ts
  tailwind.config.js
Labels: D-2

#168 refactor: 이전 상담내역 탭 재활성화
  .prettierrc
  package.json
  pnpm-lock.yaml
  src/app/Router.tsx
  src/components/ui/tabs.tsx
  src/pages/Consult/components/table/PrevCounselTable/index.tsx
  src/pages/Consult/components/table/PrevCounselTable/prevCounselTableColunm.tsx
  src/pages/Consult/components/tabs/PastConsult.tsx
  src/pages/Consult/hooks/query/usePrevCounselSessionList.tsx
  src/pages/Consult/hooks/query/usePrevMedicationCounsel.tsx
  src/pages/Consult/index.tsx
Labels: D-2

#170 refactor: :sparkles: 중재기록 작성 init 여부 플래그 추가를 통한 editState 중복 init 방지
  src/components/consult/HighlightInput.tsx
  src/store/medicineConsultStore.ts
Labels: D-2

#171 style: 💄 STT QA 관련 버그 수정
  src/assets/icon/24/pause.fill.black.svg
  src/assets/icon/24/record.fill.red.svg
  src/assets/icon/24/stop.fill.black.svg
  src/components/NavigationRight.tsx
  src/components/consult/HighlightInput.tsx
  src/components/consult/Recording.tsx
  src/pages/Consult/components/recording/AiSummary.tsx
  src/pages/Consult/components/recording/TotalRecordings.tsx
  src/pages/Consult/components/tabs/MedicineConsult.tsx
  src/pages/Consult/index.tsx
  src/store/consultTabStore.ts
Labels: D-0

#172 feat: add AccountManagement page
  src/api/api.ts
  src/app/Routes.tsx
  src/components/common/DataTable/data-table.tsx
  src/components/ui/input.tsx
  src/components/ui/tabs.tsx
  src/pages/Account/README.md
  src/pages/Account/components/AccountTableSection.tsx
  src/pages/Account/components/dialog/AccountDetailDialog.tsx
  src/pages/Account/components/dialog/BasicInfoTab.tsx
  src/pages/Account/components/dialog/PasswordChangeTab.tsx
  src/pages/Account/components/table/AccountTable.tsx
  src/pages/Account/components/table/CounselorColumns.tsx
  src/pages/Account/hooks/queries/useCounselorQuery.ts
  src/pages/Account/hooks/store/useCounselorStore.ts
  src/pages/Account/hooks/useCounselorManagement.ts
  src/pages/Account/index.tsx
  src/pages/Consult/index.tsx
  tsconfig.app.tsbuildinfo
Labels: D-0

#173 feat: :sparkles: add forbidden page
  src/api/errorHandler.ts
  src/app/Routes.tsx
Labels: D-3

#175 refactor: :recycle: remove all the functions regarding survey
  src/api/api.ts
  src/app/Routes.tsx
  src/components/common/CardContainer.tsx
  src/pages/Consult/components/tabs/ConsultCard.tsx
  src/pages/Consult/hooks/query/useConsultCard.ts
  src/pages/Consult/hooks/store/consultCardStore.ts
  src/pages/Consult/index.tsx
  src/pages/Home/components/SurveyDialog.tsx
  src/pages/Home/index.tsx
  src/pages/Survey/components/TabContent.tsx
  src/pages/Survey/components/TabTitle.tsx
  src/pages/Survey/constants/IndependentInfo/index.ts
  src/pages/Survey/constants/baseInfo/index.ts
  src/pages/Survey/constants/healthInfo/index.ts
  src/pages/Survey/constants/livingInfo/index.ts
  src/pages/Survey/constants/modal/index.ts
  src/pages/Survey/dialogs/counselSurvey/SaveCounselSurvey.tsx
  src/pages/Survey/dialogs/userInfo/ExpiredMedications.tsx
  src/pages/Survey/dialogs/userInfo/Index.tsx
  src/pages/Survey/dialogs/userInfo/InformationThirdParties.tsx
  src/pages/Survey/dialogs/userInfo/InformationUse.tsx
  src/pages/Survey/hooks/useCounselAgreeQuery.ts
  src/pages/Survey/hooks/useCounselAssistantQuery.ts
  src/pages/Survey/store/surveyInfoStore.ts
  src/pages/Survey/store/surveyTabStore.ts
  src/pages/Survey/tabs/BaseInfo.tsx
  src/pages/Survey/tabs/HealthInfo.tsx
  src/pages/Survey/tabs/IndependentInfo.tsx
  src/pages/Survey/tabs/Index.tsx
  src/pages/Survey/tabs/LivingInfo.tsx
  tsconfig.app.tsbuildinfo
Labels: D-3

#176 feat: :sparkles: add ConsentPage
  src/api/api.ts
  src/app/Routes.tsx
  src/components/consult/HighlightInput.tsx
  src/components/consult/PencilIcon.tsx
  src/components/consult/Recording.tsx
  src/hooks/useRecording.ts
  src/pages/Consult/components/WaseMedicationSurvey.tsx
  src/pages/Consult/components/recording/RecordingResult.tsx
  src/pages/Consult/components/recording/SelectSpeakerDialog.tsx
  src/pages/Consult/components/recording/TotalRecordings.tsx
  src/pages/Consult/components/table/WasteMedicationTable/index.tsx
  src/pages/Consult/components/table/WasteMedicationTable/wasteMedicationColumns.tsx
  src/pages/Consult/components/tabs/DiscardMedicine.tsx
  src/pages/Consult/components/tabs/MedicineConsult.tsx
  src/pages/Consult/hooks/query/counselRecording/useGetAiSummaryQuery.ts
  src/pages/Consult/hooks/query/counselRecording/useGetRecordingSpeakersQuery.ts
  src/pages/Consult/hooks/query/counselRecording/useGetRecordingStatusQuery.ts
  src/pages/Consult/hooks/query/counselRecording/useGetSpeechToTextQuery.ts
  src/pages/Consult/hooks/query/medicationRecord/useMedicationRecordSave.tsx
  src/pages/Consult/hooks/query/useMedicineConsultQuery.ts
  src/pages/Consult/hooks/query/wasteMedicineRecord/useWasteMedicationMutate.tsx
  src/pages/Consult/hooks/store/useWasteMedicationDisposalStore.ts
  src/pages/Consult/hooks/store/useWasteMedicationListStore.ts
  src/pages/Consult/types/MedicationRecordListDTO.ts
  src/pages/Consult/types/MedicineConsultDTO.ts
  src/pages/Consult/types/Recording.enum.ts
  src/pages/Consult/types/WasteMedicationDTO.ts
  src/pages/Home/components/SurveyDialog.tsx
  src/pages/Survey/consent.tsx
  src/pages/Survey/hooks/counselCardStore.ts
  src/pages/Survey/hooks/counseleeConsentStore.ts
  src/pages/Survey/hooks/useCounselCardQuery.ts
  src/pages/Survey/hooks/useCounseleeConsentQuery.ts
  src/pages/Survey/index.tsx
  src/store/medicineConsultStore.ts
  tsconfig.app.json
  tsconfig.app.tsbuildinfo
Labels: D-3

#177 feat: ✨관리자페이지 dialog 스타일 일치 및 유저 입력 validation 적용
  src/components/ui/buttonVariants.ts
  src/components/ui/datepicker.tsx
  src/components/ui/dialog.tsx
  src/components/ui/form-input.tsx
  src/components/ui/select.tsx
  src/components/ui/textarea.tsx
  src/components/ui/time-picker.tsx
  src/pages/Account/components/dialog/AccountDetailDialog.tsx
  src/pages/Account/components/dialog/BasicInfoTab.tsx
  src/pages/Account/components/dialog/PasswordChangeTab.tsx
  src/pages/Account/components/table/CounselorColumns.tsx
  src/pages/Consult/components/recording/DeleteRecordingDialog.tsx
  src/pages/Counselee/components/dialog/CounseleeDialog.tsx
  src/pages/Counselee/components/table/counseleeColumns.tsx
  src/pages/Session/components/CounselSessionTableSection.tsx
  src/pages/Session/components/dialog/CounseleeSearchInput.tsx
  src/pages/Session/components/dialog/CreateReservationDialog.tsx
  src/pages/Session/components/dialog/EditReservationDialog.tsx
  src/pages/Session/components/table/CounselSessionColumns.tsx
  src/pages/Session/index.tsx
  src/utils/formatDisplayText.ts
  src/utils/inputValidations.ts
Labels: D-3

#178 feat: ✨ 본상담 임시저장/상담완료 Dialog 추가
  src/assets/home/complete-consult.webp
  src/assets/home/finish-consult.webp
  src/pages/Consult/components/CompleteConsultDialog.tsx
  src/pages/Consult/components/FinishConsultDialog.tsx
  src/pages/Consult/components/TemporarySaveDialog.tsx
  src/pages/Consult/index.tsx
Labels: D-1

#180 feat: ✨ 발화자 선택 화면 전체 수정 및 색상 정의 변경
  src/app/App.tsx
  src/app/reduxHooks.ts
  src/app/store.ts
  src/components/NavigationRight.tsx
  src/components/consult/Recording.tsx
  src/hooks/useRecording.ts
  src/pages/Consult/components/recording/SelectSpeakerDialog.tsx
  src/pages/Consult/components/recording/TotalRecordings.tsx
  src/pages/Consult/components/tabs/MedicineConsult.tsx
  src/pages/Consult/hooks/query/counselRecording/useGetRecordingStatusQuery.ts
  src/pages/Consult/index.tsx
  src/pages/Consult/types/Recording.enum.ts
  src/reducers/navigationReducer.ts
  src/reducers/tabReducer.ts
  src/store/navigationStore.ts
  tailwind.config.js
Labels: D-2

#182 fix: :bug: fix time-picker and lint errors
  src/components/ui/time-picker.tsx
  src/pages/Survey/components/tabs/BasicInfo.tsx
  src/pages/Survey/components/tabs/HealthInfo.tsx
  src/pages/Survey/hooks/useCounselCardQuery.ts
Labels: D-0

#183 fix: :green_heart: fix build error
  src/api/api/counsel-card-controller-api.ts
  tsconfig.app.tsbuildinfo
Labels: bug, D-3, D-0

#184 fix(QA): 🐛 STT 관련 QA 대응
  src/components/NavigationRight.tsx
  src/components/consult/HighlightInput.tsx
  src/pages/Consult/components/FinishConsultDialog.tsx
  src/pages/Consult/components/TemporarySaveDialog.tsx
Labels: D-3

#185 refactpr: 홈 QA 반영
  src/components/common/NavigationLeft.tsx
  src/components/ui/calendar.tsx
  src/components/ui/datepicker.tsx
  src/pages/Home/components/AssignDialog.tsx
  src/pages/Home/components/TodayScheduleTable/todayScheduleTableColumn.tsx
  src/pages/Home/index.tsx
Labels: D-3

#186 refactor: 본상담 QA 항목 반영
  src/assets/insurance.png
  src/assets/kims.png
  src/assets/kpic.png
  src/assets/nulpeum.png
  src/assets/site/insurance.webp
  src/assets/site/kims.webp
  src/assets/site/kpic.webp
  src/assets/site/nulpeum.webp
  src/components/common/DataTable/counsel-status-cell.tsx
  src/components/common/DataTable/medicine-search-cell.tsx
  src/components/common/DataTable/select-cell.tsx
  src/components/common/DataTable/text-input-cell.tsx
  src/components/consult/HighlightInput.tsx
  src/components/ui/buttonVariants.ts
  src/hooks/useCounselSessionQueryById.ts
  src/hooks/useUpdateCounselSessionStatus.ts
  src/pages/Consult/components/EditConsultDialog.tsx
  src/pages/Consult/components/FinishConsultDialog.tsx
  src/pages/Consult/components/TemporarySaveDialog.tsx
  src/pages/Consult/components/UsableSiteList.tsx
  src/pages/Consult/components/WaseMedicationSurvey.tsx
  src/pages/Consult/components/tabs/DiscardMedicine.tsx
  src/pages/Consult/components/tabs/PastConsult.tsx
  src/pages/Consult/hooks/query/wasteMedicineRecord/useWasteMedicationMutate.tsx
  src/pages/Consult/index.tsx
  src/pages/Home/components/AssignDialog.tsx
  src/pages/Layout.tsx
  src/pages/Session/components/CounselSessionTableSection.tsx
Labels: D-3

#188 fix: :bug: STT 완료된 상담 진입 시 항상 SNB 가 펼쳐지는 버그 수정
  src/pages/Consult/index.tsx
  src/pages/Home/index.tsx
Labels: D-3

#189 feat: toast등 저장 동작 QA 반영
  src/api/errorHandler.ts
  src/components/common/DataTable/data-table.tsx
  src/components/consult/HighlightInput.tsx
  src/components/ui/buttonVariants.ts
  src/components/ui/costom-toast.tsx
  src/components/ui/datepicker.tsx
  src/components/ui/sonner.tsx
  src/components/ui/table.tsx
  src/components/ui/time-picker.tsx
  src/hooks/useCounselSessionQuery.ts
  src/pages/Account/components/dialog/AccountDetailDialog.tsx
  src/pages/Account/components/dialog/BasicInfoTab.tsx
  src/pages/Account/components/dialog/PasswordChangeTab.tsx
  src/pages/Consult/components/tabs/MedicineConsult.tsx
  src/pages/Consult/hooks/query/medicationRecord/useMedicationRecordSave.tsx
  src/pages/Consult/hooks/query/wasteMedicineRecord/useSaveWasteMedication.ts
  src/pages/Consult/hooks/query/wasteMedicineRecord/useWasteMedicationMutate.tsx
  src/pages/Consult/index.tsx
  src/pages/Session/components/CounselSessionTableSection.tsx
  src/pages/Session/components/dialog/CounseleeSearchInput.tsx
  src/pages/Session/components/dialog/CreateReservationDialog.tsx
  src/pages/Session/components/dialog/EditReservationDialog.tsx
  src/pages/Session/components/table/CounselSessionTable.tsx
  src/pages/Survey/index.tsx
Labels: D-0

#192 refactor: :recycle: refactor counselCard
  package.json
  pnpm-lock.yaml
  src/api/api.ts
  src/api/api/counsel-card-controller-api.ts
  src/api/models/allergy-dto.ts
  src/api/models/medication-side-effect-dto.ts
  src/pages/Consult/components/tabs/ConsultCard.tsx
  src/pages/Survey/components/tabs/HealthInfo.tsx
  src/pages/Survey/hooks/useCounselCardQuery.ts
  src/pages/Survey/index.tsx
  tsconfig.app.tsbuildinfo
Labels: D-1

#191 feat: :passport_control: refactor router by roles
  src/api/errorHandler.ts
  src/app/Routes.tsx
Labels: D-2

#194 refactor: :recycle: refactor navigation
  src/pages/Session/components/table/CounselSessionTable.tsx
  src/pages/Survey/index.tsx
Labels: D-3

#195 refactor: :lipstick: refactor button-group
  src/components/ui/button-group.tsx
  src/components/ui/buttonVariants.ts
  src/pages/Session/components/CounselSessionTableSection.tsx
  src/pages/Session/components/table/CounselSessionTable.tsx
Labels: D-3

#196 refactor: :recycle: refactor survey routing
  src/pages/Consult/components/tabs/ConsultCard.tsx
  src/pages/Survey/hooks/useCounselCardQuery.ts
  src/pages/Survey/index.tsx
Labels: bug, D-0

#197 refactor: 🎨 Recording 관련 책임 분리
  src/components/NavigationRight.tsx
  src/components/common/DataTable/table-cell.tsx
  src/components/consult/Recording.tsx
  src/components/table/TableCell.tsx
  src/hooks/useRecording.ts
  src/pages/Consult/components/recording/SelectSpeakerDialog.tsx
  src/pages/Consult/hooks/query/counselRecording/useGetRecordingStatusQuery.ts
  src/pages/Consult/index.tsx
  src/pages/Home/index.tsx
Labels: D-3

#198 refactor: :truck: enable none user to logout
  src/components/common/CollegeMessage.tsx
  src/components/common/ConsultCount.tsx
  src/components/common/NavigationLeft.tsx
  src/components/common/NavigationLeftMenu.tsx
  src/components/common/NavigationRight.tsx
  src/components/common/Tooltip.tsx
  src/components/consult/HighlightInput.tsx
  src/pages/Home/components/TodayScheduleTable/todayScheduleTableColumn.tsx
  src/pages/Layout.tsx
Labels: D-3

#199 fix: :passport_control: allow user to access counselee page
  src/app/Routes.tsx
  src/components/common/NavigationLeft.tsx
Labels: D-3

#201 fix: 🐛 저장 버튼 클릭 시, 지연 없이 status 변경
  src/hooks/useRecording.ts
Labels: D-3

#202 refactor: 유저 권한 관련 QA 반영
  src/api/base.ts
  src/api/common.ts
  src/app/Routes.tsx
  src/components/common/NavigationLeft.tsx
  src/context/AuthContext.tsx
  src/pages/Home/components/TodayScheduleTable/index.tsx
  src/pages/Home/components/TodayScheduleTable/todayScheduleTableColumn.tsx
  src/pages/Home/hooks/query/useCounselActiveDate.ts
  src/pages/Home/index.tsx
  src/pages/Layout.tsx
  src/utils/constants.ts
Labels: D-2

#203 fix: ROLE_NONE 유저 홈 메뉴 표기
  src/components/common/NavigationLeft.tsx
Labels: D-3

#206 fix: 🎨 useRecording hook/store 분리
  src/components/RouteTracker.tsx
  src/components/common/NavigationLeft.tsx
  src/components/common/NavigationRight.tsx
  src/components/consult/PencilIcon.tsx
  src/components/consult/Recording.tsx
  src/hooks/useRecording.ts
  src/pages/Consult/components/CheckLeaveOutDialog.tsx
  src/pages/Consult/components/FinishConsultDialog.tsx
  src/pages/Consult/components/TemporarySaveDialog.tsx
  src/pages/Consult/components/recording/AiSummary.tsx
  src/pages/Consult/components/recording/RecordingResult.tsx
  src/pages/Consult/components/recording/SelectSpeakerDialog.tsx
  src/pages/Consult/components/recording/TotalRecordings.tsx
  src/pages/Consult/components/tabs/MedicineConsult.tsx
  src/pages/Consult/hooks/store/useRecordingStore.ts
  src/pages/Consult/index.tsx
Labels: D-3

#207 feat: ✨ 본상담 녹음 중 다른 메뉴로 이탈 시 현재 녹음 파일 저장
  src/components/common/NavigationLeft.tsx
  src/hooks/useRecording.ts
  src/pages/Consult/components/CheckLeaveOutDialog.tsx
  src/pages/Consult/components/FinishConsultDialog.tsx
  src/pages/Consult/components/TemporarySaveDialog.tsx
  src/pages/Consult/index.tsx
  src/pages/Consult/types/Recording.enum.ts
Labels: D-3

#208 feat: ✨ add cursor rules
  .cursor/rules/cursorrule.mdc
  package.json
  pnpm-lock.yaml
Labels: enhancement, D-0

#209 fix: resolve qa errors
  src/components/ui/Header.tsx
  src/components/ui/card-section.tsx
  src/pages/Consult/components/tabs/ConsultCard.tsx
  src/pages/Consult/index.tsx
  src/pages/Survey/components/tabs/BasicInfo.tsx
  src/pages/Survey/components/tabs/HealthInfo.tsx
  src/pages/Survey/components/tabs/IndependentLivingAssessment.tsx
  src/pages/Survey/components/tabs/LivingInfo.tsx
  src/pages/Survey/consent.tsx
  src/pages/Survey/hooks/counselCardStore.ts
  src/pages/Survey/hooks/useCounselCardQuery.ts
  src/pages/Survey/index.tsx
  src/utils/constants.ts
Labels: D-1

#210 fix: 본상담 의약물기록 QA
  src/api/models/select-medication-record-hist-res.ts
  src/components/common/DataTable/data-table.tsx
  src/components/common/DataTable/medicine-search-cell.tsx
  src/components/ui/buttonVariants.ts
  src/components/ui/card.tsx
  src/components/ui/datepicker.tsx
  src/components/ui/pagination.tsx
  src/hooks/useContentWidth.tsx
  src/pages/Consult/components/TabContents.tsx
  src/pages/Consult/components/table/MedicineRecordTable/index.tsx
  src/pages/Consult/components/table/MedicineRecordTable/medicineRecordTableColumns.tsx
  src/pages/Consult/components/table/PrevCounselTable/prevCounselTableColunm.tsx
  src/pages/Consult/components/tabs/MedicineMemo.tsx
  src/pages/Consult/hooks/store/useWasteMedicationListStore.ts
  src/pages/Consult/index.tsx
Labels: D-3

#212 fix: resolve several bugs
  src/components/common/DataTable/data-table.tsx
  src/pages/Consult/components/table/MedicineRecordTable/medicineRecordTableColumns.tsx
  src/pages/Session/components/table/CounselSessionColumns.tsx
  src/utils/constants.ts
  src/utils/inputValidations.ts
Labels: D-3

#213 refactor: :lipstick: update table UI
  src/pages/Account/components/AccountTableSection.tsx
  src/pages/Consult/components/tabs/ConsultCard.tsx
  src/pages/Counselee/components/CounseleeTableSection.tsx
  src/pages/Counselee/components/dialog/CounseleeDialog.tsx
  src/pages/Session/components/CounselSessionTableSection.tsx
  src/pages/Session/components/FilterSection.tsx
  src/pages/Session/components/dialog/CreateReservationDialog.tsx
  src/pages/Session/components/table/CounselSessionColumns.tsx
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: bug, D-3

#214 fix: 본상담 중재기록 에디터 에러케이스 대응, 상담 히스토리 로직 수정
  src/components/common/DataTable/medicine-search-cell.tsx
  src/components/consult/HighlightInput.tsx
  src/pages/Consult/components/table/PrevCounselTable/index.tsx
  src/pages/Consult/components/tabs/PastConsult.tsx
  src/pages/Consult/index.tsx
Labels: D-3

#215 fix: 의약물 기록 삭제 query invalidate 미동작 수정
  src/components/ui/datepicker.tsx
  src/pages/Consult/hooks/useInitializeAllTabsData.ts
Labels: D-3

#216 feat: ✨ 상담 진행 중 상태에서 이탈 시, 임시저장 기능 추가
  src/components/common/NavigationLeft.tsx
  src/pages/Consult/index.tsx
Labels: D-3

#217 feat: 상담삭제 dialog 추가
  src/pages/Session/components/SessionDeleteDialog.tsx
  src/pages/Session/components/table/CounselSessionColumns.tsx
Labels: D-3

#218 refactor: 👽 update survey api changes
  package.json
  pnpm-lock.yaml
  src/api/.openapi-generator/FILES
  src/api/api/counsel-card-controller-api.ts
  src/api/api/default-api.ts
  src/api/models/add-and-update-medication-record-hist-req.ts
  src/api/models/index.ts
  src/api/models/select-medication-record-hist-res.ts
  src/api/models/update-counsel-card-req.ts
  src/pages/Consult/components/tabs/ConsultCard.tsx
  src/pages/Session/components/FilterSection.tsx
  src/pages/Session/components/table/CounselSessionColumns.tsx
  src/pages/Survey/components/tabs/LivingInfo.tsx
  src/pages/Survey/hooks/useCounselCardQuery.ts
Labels: D-3

#219 fix: 상담 히스토리 상담내용 요약 AI 요약으로 변경
  src/components/common/NavigationLeft.tsx
  src/pages/Consult/components/tabs/PastConsult.tsx
Labels: D-3

#220 docs: :memo: fix readme typo
  README.md
  src/pages/Counselee/components/dialog/CounseleeDialog.tsx
  src/pages/Survey/hooks/useCounselCardQuery.ts
  src/pages/Survey/index.tsx
  tsconfig.app.tsbuildinfo
Labels: documentation, D-3
